name-template: '$BRANCH_NAME'
tag-template: '$BRANCH_NAME'

categories:
  - title: '🚀 Features'
    labels:
      - 'feat'
      - 'task'
      - 'chore'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

autolabeler:
  - label: fix
    title:
      - '/\bfix\b/i'

  - label: task
    title:
      - '/\btask\b/i'

  - label: 'feat'
    title:
       - '/\feat\b/i'

template: |
  ## Changes

  $CHANGES