categories:
  - title: "🚀 Features"
    labels:
      - feat
      - task
      - chore

  - title: "🐛 Bug Fixes"
    labels:
      - fix
      - bugfix
      - bug

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'

autolabeler:
  - label: fix
    title:
      - '/\bfix\b/i'

  - label: task
    title:
      - '/\btask\b/i'

  - label: feat
    title:
      - '/\bfeat\b/i'

template: |
  ## Changes

  $CHANGES