name: Release Drafter

on:
  push:
    branches:
      - "release/*"

jobs:
  update_release_draft:
    runs-on: ubuntu-latest

    steps:
      - name: Extract version
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/heads/release/}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Update release draft
        uses: release-drafter/release-drafter@v6
        with:
          name: ${{ steps.version.outputs.VERSION }}
          tag: ${{ steps.version.outputs.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}